---
- name: Copy spec.json and bootnodes.txt to remote machine
  copy: src={{ item }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }} force=yes
  when: spec_json != ""
  with_items:
    - "{{ spec_json }}"
    - "{{ bootnodes_txt }}"

- name: Download spec.json and bootnodes.txt
  get_url: url={{ item }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/dai-deployment/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/dai-deployment/bootnodes.txt"
  when: spec_json == ""
